//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int idQualification { get; set; }
        public int idSubjectGroup { get; set; }
        public int idStudent { get; set; }
        public int test { get; set; }
        public int homeWork { get; set; }
        public int conduct { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual SubjectGroup SubjectGroup { get; set; }
    }
}
