//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectGroup
    {
        public SubjectGroup()
        {
            this.Qualification = new HashSet<Qualification>();
        }
    
        public int idSubjectGroup { get; set; }
        public int idGroup { get; set; }
        public int idSubject { get; set; }
        public int idTeacher { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Qualification> Qualification { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
