//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.SubjectGroup = new HashSet<SubjectGroup>();
        }
    
        public int idSubject { get; set; }
        public string name { get; set; }
        public int year { get; set; }
    
        public virtual ICollection<SubjectGroup> SubjectGroup { get; set; }
    }
}
