//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlSchoolEntities : DbContext
    {
        public ControlSchoolEntities()
            : base("name=ControlSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Level> Level { get; set; }
        public DbSet<Result> Result { get; set; }
        public DbSet<ResultSubjectStudent> ResultSubjectStudent { get; set; }
        public DbSet<Section> Section { get; set; }
        public DbSet<SectionLevel> SectionLevel { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<StudentLevel> StudentLevel { get; set; }
        public DbSet<StudentSection> StudentSection { get; set; }
        public DbSet<StudentSubject> StudentSubject { get; set; }
        public DbSet<Subject> Subject { get; set; }
    }
}
