//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentClasses = new HashSet<StudentClasses>();
            this.StudentSubject = new HashSet<StudentSubject>();
        }
    
        public int id_student { get; set; }
        public string name { get; set; }
        public string lastname1 { get; set; }
        public string lastname2 { get; set; }
        public string gender { get; set; }
        public int age { get; set; }
        public int telephone { get; set; }
    
        public virtual ICollection<StudentClasses> StudentClasses { get; set; }
        public virtual ICollection<StudentSubject> StudentSubject { get; set; }
    }
}
