//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.ResultSubjectStudent = new HashSet<ResultSubjectStudent>();
            this.StudentSubject = new HashSet<StudentSubject>();
        }
    
        public int Id { get; set; }
        public string Subject1 { get; set; }
    
        public virtual ICollection<ResultSubjectStudent> ResultSubjectStudent { get; set; }
        public virtual ICollection<StudentSubject> StudentSubject { get; set; }
    }
}
