//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Classes = new HashSet<Classes>();
            this.TeacherSubject = new HashSet<TeacherSubject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Lastname1 { get; set; }
        public string Lastname2 { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public int Telephone { get; set; }
    
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual ICollection<TeacherSubject> TeacherSubject { get; set; }
    }
}
