//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Classes = new HashSet<Classes>();
            this.TeacherSubject = new HashSet<TeacherSubject>();
        }
    
        public int id_teacher { get; set; }
        public string name { get; set; }
        public string lastname1 { get; set; }
        public string lastname2 { get; set; }
        public string gender { get; set; }
        public int age { get; set; }
        public int telephone { get; set; }
    
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual ICollection<TeacherSubject> TeacherSubject { get; set; }
    }
}
